import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import { useFirekeyMutation } from '../utils/useFirebase'
import { enableNotifications, onNotification } from '../utils/utils'

const Home: NextPage = () => {
  const [customMsg, setCustomMsg] = useState('')
  const firebaseToken = useFirekeyMutation()

  return (
    <div>
      <Head>
        <title>Pushy Push JR</title>
        <meta name='description' content='Generated by Pushy Push Jr' />
        <link rel='icon' href='/PushyPushJRImage.ico' />
        <link rel='manifest' href='/manifest.json' />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
      </Head>

      <div>
        <div className="container-fluid">
          <div className="jumbotron">
            <div className="row">
              <div className="col-sm-9">
              <h1>Welcome to Pushy Push JR!</h1>      
              
                <h3>Project Summary</h3>
                <p>To have alerts be sent to users when they don’t have app.conductiv.com open so we can get more user engagement</p>
              </div>
              <div className="col-sm-3">
                <img className="img-responsive img-circle" src='/PushyPushJRImage.png' alt='Pushy Push JR Image' />
              </div>
            </div>
            <div className='col-sm-9'>
              <div>
                <h4>Get started by enabling Notifications
              
                <button type="button" className='btn btn-primary' onClick={enableNotifications}>Enable Notification(s)</button></h4>
              </div>
            </div>
          </div>
        </div>
      
          
        
      <div className='container'>
        <div className='row'>
          
          <div className='col-sm-4'>
            <div>
            
              <div><h3>Send Test Push &rarr;</h3></div>
              
              <div><p>Send Test Push Notification from Pushy Push JR!.</p></div>
              <button type="button" className="btn btn-primary" onClick={() => onNotification('Lets Go Pushy Push Jr!')}>Send Test</button>
            </div>
          </div>
          <div className='col-sm-8'>
            <div className="row">
              <div className="col-sm-3"><div><h3>Enter Custom Push &rarr;</h3></div></div>
              <div className="col-sm-3"><input type="text" className="form-control" onChange={(input) => setCustomMsg(input.currentTarget.value)} /></div>
            
              <div className="col-sm-3">
              <button type="button" className="btn btn-primary" onClick={() => onNotification(customMsg)}>
              Send Custom
              </button>
              </div>
            </div>
          </div>
          
        </div>
        <div><br/><br/></div>
        <div className='row'>
          
          <div className='col-sm-9'>
            <div className="panel panel-default">
              <div className="panel-heading">firebaseToken</div>
              <div className="panel-body"><p>{firebaseToken}</p></div>
            </div>
          </div>
          
          
        </div>
      </div>
        
      </div>
    </div>

  )
}

export default Home
